name: trueclient
description: "The TrueClient Flutter Package is a complete solution for easily integrating OTP (One-Time Password) verification into your mobile applications developed with Flutter."
version: 1.0.0
repository: https://github.com/ChakibAA/TrueClient-Flutter-Package
homepage: https://trueclientdz.com/

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.6.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^4.0.0
  http_mock_adapter: ^0.6.1
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17



topics:
  - otp
  - algeria
  - phone
  - validation